sudo: required

language: c

services:
  - docker

before_install:
  - docker pull odanoburu/haskell-gf:3.9
  - mkdir rgl

script:
  - docker run --mount src="$(pwd)",target=/home,type=bind odanoburu/haskell-gf:3.9 /bin/sh -c "cd /home/; runghc Make.hs build all --verbose ;"
  - docker run --mount src="$(pwd)",target=/home,type=bind odanoburu/haskell-gf:3.9 /bin/sh -c "cd /home/; export GF_LIB_PATH=/home/rgl; sh Make.sh --dest=rgl --verbose ;"
